### ISSUE TITLE
Bug: False flags when importing RBY teams

### ISSUE THREAD

**Issue by ShiraTheMogul** [GregLyons/poke-team#4]
Presumably, this occurs for GSC as well.

When importing a Gen 1 team, you will have "No Ability" get flagged despite requesting the format Pokepaste/Showdown uses. I believe that there should be an exception made when plugging these in. Abilities do not exist in RBY or GSC.
![image](https://user-images.githubusercontent.com/36418502/163276125-f6a063b0-6018-4147-811c-fdf2910ca201.png)

Once removed, it will check for natures, despite RBY/GSC not having natures at all. 
![image](https://user-images.githubusercontent.com/36418502/163275941-20d1c3dd-bc97-4378-9896-e4d69fff21b1.png)

**Comment by GregLyons** [comment]
I added a few lines that'll ignore the ability, held item, and nature checks if they don't exist in the given gen (before gen 3, before gen 2, before gen 3, respectively). Here's a screenshot of the import working with both "Ability: No Ability", and with no Ability at all. This change should be live now.

![import-gen1](https://user-images.githubusercontent.com/89315619/163296396-9d3f06c2-64bb-46d8-84c7-f12b9892b8ef.png)
